"""fix character class and background nullable

Revision ID: 0549f5dad877
Revises: 0c6c499dec66
Create Date: 2026-08-31 19:41:52.928019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0549f5dad877'
down_revision: Union[str, Sequence[str], None] = '0c6c499dec66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'background_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'background_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
