"""add character classes backgrounds and spells

Revision ID: 0c6c499dec66
Revises: ff83fb7a2b16
Create Date: 2026-08-31 14:18:13.978160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6c499dec66'
down_revision: Union[str, Sequence[str], None] = 'ff83fb7a2b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=50), nullable=False),
    sa.Column('casting_time', sa.String(length=50), nullable=False),
    sa.Column('spell_range', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('character_spells',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'spell_id')
    )
    op.add_column('characters', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('background_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'characters', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(None, 'characters', 'backgrounds', ['background_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'background_id')
    op.drop_column('characters', 'class_id')
    op.drop_table('character_spells')
    op.drop_table('spells')
    op.drop_table('classes')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###
